# Generated by Django 5.1 on 2024-08-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_commentimage_topic_comment_quoted_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
