# Generated by Django 5.1 on 2024-09-10 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_comment_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='quoted_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoting_topics', to='api.topic'),
        ),
    ]
