# Generated by Django 5.1 on 2024-09-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_topic_image_1_remove_topic_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.DeleteModel(
            name='TopicImage',
        ),
    ]
