# Generated by Django 5.1 on 2024-09-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_topic_image_1_topic_image_2_topic_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='post_comments/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='post_comments/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='post_comments/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='post_comments/'),
        ),
    ]
