# Generated by Django 5.1 on 2024-10-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
    ]
